### ISSUE TITLE
embeddings: work out a standard format  for embedding results

### ISSUE THREAD

**Issue by josephjclark** [OpenFn/apollo#122]
I need help on this one

We are setting up a standard embeddings layer, so it's super easy to plug in new embedded datasets and search them.

One thing that's missing is a standard format for the returned data.

Ie, when I do `results = store.search("what is salesforce?")`, what does `results look like?

In JSON (and I'm a long type JavaScript sufferer so I often think in JSON) I'd imagine an array of results like this:
```
[{
   doc: "Salesforce is a CRM platform used by..."
   score: 0.5
   source: {
      url : "https://docs.openfn.org/...",
      title: "Salesforce Adaptor",
      collection_name: "docsite.adaptors"
   }
}]
```

This ticket is to work out exactly what that object structure is, and how it should be captured in Python (I guess a class lie RagResult or EmbeddedDoc or something)

The end goal here is that when some service uses RAg, there is some visibility about what its inputs are. I'm thinking in particular of something like the DHIS2 AI helper, which lists its sources when you ask a question:

![Image](https://github.com/user-attachments/assets/8cd07025-10f2-4af9-b43f-a933ea21a84e)

If the underlying embeddings framework has a standard means of reporting a) text and b) the source of that text, then we stand a chance of being able to build really good quality front-ends like DHIS2's.

Note that although the interface should support all this extra context stuff, stores do not _have_ to support it.

**Comment by hanna-paasivirta** [comment]
Some considerations:

- We could adjust our VectorStore class to return the collection name and the similarity search method that was passed in when instantiating it in e.g. example.py . I'm not sure this would be very useful.
- Our vector stores would not currently have metadata for each split like "Salesforce adaptor" part of the adaptor docs. When creating the vector store, however, we can split the text in a more detailed rule-based way (instead of chunks) and assign names for each part to save as metadata. 
- When we search for top k similar texts, this will just return the text and the metadata. Some vector stores have a similarity_search_with_score method, or similarity_search_with_relevance_scores method. I could replace the current multipurpose as_retriever(search_type, search_kwargs) to use this instead. Other types of similarity searches would then require adding new functions into the VectorStore class (e.g. max_marginal_relevance_search, threshold-based search). Some of these will still not output a similarity score though. We might use a mix of methods within one service/project in different parts of an LLM-based pipeline. I would suggest we stick with the multipurpose one for now, and add additional search functions once we know we need a score output for a project.

Suggestion:
We could return a dictionary or JSON with the **retrieved** **text** and an **additional information** field, the exact contents of which will be different for every project (and potentially, each new similarity function). The additional information field could always contain the **metadata** of the vector store (whatever that metadata itself contains). If we add a method that can output a score, we can add that in the additional information as well. In summary, we can always expect there to be a text, but if we want something else, we need to know something about the project vector store and the similarity search method used.

Example:

```py
[
    {
        'text': 'Salesforce is a CRM platform used by...', # named this text to distinguish from LangChain document objects
        'additional_information': { 
            'metadata': {
                'original_file' : 'example.json', # this is added automatically as a metadata field
                'project_specific_metadata_field_name_a' : 'Chapter 1 Adaptors',
                'project_specific_metadata_field_name_b' : 'Section 2 Salesforce Adaptor',
                'project_specific_metadata_field_name_c' : 'Core adaptors'
            },
            'score': 0.7 # case-specific whether this field is included – will need to know which sim method was used
        }
    }
]
```

**Comment by josephjclark** [comment]
I like it - what about simplifying a little to:
```
{ text, metadata, score }
```

Where metadata is totally arbitrary, store-specific information. The value of `score` is search-and-store-specific, subject to query parameters. Since the client knows what parameters it used I'm not really sure we need to write anything about the method used? But we can also come back and add stuff later

Rather than passing a dict around in pythonland, we should create a class like `new SearchResult(text, metadata={ dict }, score=number)`. So calling `store.search(...)` will return a list of `SearchResults`. Maybe we need a handy `toJSON()` function to generate a dict to return straight to the web layer 🤔 

Thinking about it, we're going to have to add the ability to add_docs to capture that information! Does that mean we also need a standard Doc object, like `new Doc(text, { **metadata })`?

Let's talk this through tomorrow!

**Comment by josephjclark** [comment]
Note to me: we're using langchain classes to add documents, which support metadata etc, and there's no need to create our own!
